### PR TITLE
[release] Kelp v3.2.0

### PR DESCRIPTION
**Pull request by cerqiest**
This PR is a **draft** and does not include all the features to be included in Kelp v3.2.0.

This PR adds:
- Better route loading (now supports default options)
- CLI tool for generating routes
- `X-Powered-By` header
- Better formatted error pages
- Always set headers option
- JSDoc Comments
- Bug fixes

### CODE REVIEW

**Comment by cerqiest** [comment]
@blockarchitech Still waiting for error handler to be fixed

**Review by blockarchitech — APPROVED** [review]
LGTM

**Review by blockarchitech — APPROVED** [review]
LGTM

**Comment by cerqiest** [comment]
How is this a fix?

**Pull request merged**
