### PR TITLE
Added mocha tests, full package.json, refactor

### PR DESCRIPTION
**Pull request by blockarchitech**
This PR will prepare for NPM publishing on the `znci` account, not `zncidev`.

### CODE REVIEW

**Comment by blockarchitech** [comment]
This is no longer correct as this will be an NPM module. Please re-read the description.

**Comment by blockarchitech** [comment]
docs.znci.dev exists

We will have a proper README at some point. Out of scope of this PR.

**Comment by TheUnium** [comment]
looks good to me, npm packages should not include example files.

**Comment by blockarchitech** [comment]
Tests do work! Took me a while to make them 😄

**Comment by blockarchitech** [comment]
@zNotChill Awaiting your review

**Comment by blockarchitech** [comment]
See https://mochajs.org

**Review by zNotChill — APPROVED** [review]
figured out how to review im so smart

**Pull request merged**
